# v2:
# https://v2.gost.run/en/getting-started/
# https://github.com/ginuerzh/gost
# docker.io/ginuerzh/gost:latest

# v3:
# https://gost.run/en/getting-started/configuration-overview/
# https://github.com/go-gost/gost

services:
  gost-proxy-server:
    container_name: gost-proxy-server
    # image: docker.io/ginuerzh/gost:latest
    # image: docker.io/go-gost/gost:latest
    image: docker.io/aanno/gost:latest
    ports:
      - 127.0.0.1:8008:8008
      - 127.0.0.1:1080:1080
    # dns:
      # https://de.getflix.com.au/setup/dns-servers/
      # Deutschland - Frankfurt - no vpn
      # - 54.93.169.181
      # Großbritannien - London - no vpn
      # - 212.71.249.225
      # Dänemark - with vpn
      # - 82.103.129.240
    cap_add:
      - NET_ADMIN
      # - NET_RAW
    # privileged: true
    devices:
      - /dev/net/tun
      - /dev/null
    # security_opt:
      # - "label=type:legulas_mariadb.process"
      # - "label=disable"
      # - "label=type:ovpn_container.process"
    # command: -C /config/config.txt
    # not with podman rootless
    # otherwise very difficult to get IP (or use localhost)
    # network_mode: "host"
    restart: unless-stopped
    networks:
      - getflix
    volumes:
      - ./config/gost.yml:/etc/gost/gost.yml:z,ro
      # - ./config/resolv.conf:/etc/resolv.conf:z,ro
      - ./config:/config:z,ro

# podman network create --dns 54.93.169.181 getflix
networks:
  getflix: 
    external: true
