from docker.io/library/eclipse-temurin:17-alpine

ENV userid=1000 MAVEN_VERSION=3.9.11
RUN adduser -h /home/vscode -s /bin/sh -G wheel -G users -D -u $userid vscode

ADD apache-maven-${MAVEN_VERSION} /opt/maven

USER vscode
WORKDIR /workspaces/java

COPY .bashrc /home/vscode/.bashrc

# https://unix.stackexchange.com/questions/640179/busybox-equivalent-for-bashrc
ENV ENV="/home/vscode/.bashrc"
