from docker.io/library/eclipse-temurin:17-alpine

# ENV userid=1001
ENV userid=1000
RUN adduser -h /home/vscode -s /bin/sh -G wheel -G users -D -u $userid vscode

USER vscode
WORKDIR /workspaces/java
