# https://gost.run/en/getting-started/configuration-overview/
# https://gost.run/en/reference/configuration/file/
services:
- name: proxy-socks5
  addr: ":1080"
  handler:
    type: socks5
  listener:
    type: tcp
    auther: auther-0
- name: proxy-http
  addr: ":8080"
  handler:
    type: http
  listener:
    type: tcp
    auther: auther-0

authers:
- name: auther-0
  auths:
  - username: ${REMOTE_PROXY_USER1}
    password: ${REMOTE_PROXY_PW1}
  - username: ${REMOTE_PROXY_USER2}
    password: ${REMOTE_PROXY_PW2}
  - username: ${REMOTE_PROXY_USER3}
    password: ${REMOTE_PROXY_PW3}

log:
  output: stderr
  level: info
  format: json
  rotation:
    maxSize: 100
    maxAge: 10
    maxBackups: 3
    localTime: false
    compress: false
