# https://gost.run/en/getting-started/configuration-overview/
# https://gost.run/en/reference/configuration/file/
services:
- name: proxy-http
  addr: ":8080"
  handler:
    type: http
    chain: chain-1
  listener:
    type: tcp
- name: proxy-socks5
  addr: ":1080"
  handler:
    type: socks5
    chain: chain-0
  listener:
    type: tcp

chains:
- name: chain-0
  hops:
  - name: hop-0
    nodes:
    - name: node-0
      addr: $REMOTE_SOCKS
      connector:
        type: socks5
        auth:
          username: $REMOTE_PROXY_USER
          password: $REMOTE_PROXY_PW
      dialer:
        type: tcp
        auth:
          username: $REMOTE_PROXY_USER
          password: $REMOTE_PROXY_PW
- name: chain-1
  hops:
  - name: hop-1
    nodes:
    - name: node-1
      addr: $REMOTE_PROXY
      connector:
        type: http
        auth:
          username: $REMOTE_PROXY_USER
          password: $REMOTE_PROXY_PW
      dialer:
        type: tcp
        auth:
          username: $REMOTE_PROXY_USER
          password: $REMOTE_PROXY_PW

authers:
- name: auther-0
  auths:
  - username: user1
    password: pass1
  - username: user2
    password: pass2

log:
  output: stderr
  level: debug
  format: json
  rotation:
    maxSize: 100
    maxAge: 10
    maxBackups: 3
    localTime: false
    compress: false
