services:
  openvpn-client:
    container_name: openvpn-client
    # image: docker.io/ginuerzh/gost:latest
    # image: docker.io/go-gost/gost:latest
    build: .
    ports:
      - 1080:1080
      - 1080:1080/udp
      - 3128:3128
    dns:
      # germany - Frankfurt - no vpn
      - 54.93.169.181
      # uk - London - no vpn
      - 212.71.249.225
    cap_add:
      - NET_ADMIN
    # privileged: true
    devices:
      - /dev/net/tun
      - /dev/null
    userns_mode: keep-id
    # network_mode: "host"
    security_opt:
      - "label=disable"
      - "label=type:ovpn_container.process"
    # command: -C /config/config.txt
    # not with podman rootless
    # otherwise very difficult to get IP (or use localhost)
    entrypoint: ["/usr/bin/supervisord", "-c", "/config/supervisord.conf", "-n"]
    restart: unless-stopped
    volumes:
      - ./config:/config:z,ro
