version: '3.3'
services:
  wikidb:
    image: mongo
    expose:
      - 27017
    command: '--smallfiles --bind_ip wikidb'
    environment:
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/mongo:/data/db
  wikijs:
    image: requarks/wiki:latest
    links:
      - wikidb
    depends_on:
      - wikidb
    ports:
      - 3000:80
    environment:
      WIKI_ADMIN_EMAIL: admin@example.com
    volumes:
      - ./config.yml:/var/wiki/config.yml
