#!/bin/bash -x

. .env
REMOTE_PROXY="${REMOTE_PROXY_HOST}:${REMOTE_PROXY_PORT}"
REMOTE_SOCKS="${REMOTE_SOCKS_HOST}:${REMOTE_SOCKS_PORT}"
export REMOTE_PROXY REMOTE_SOCKS REMOTE_PROXY_PORT REMOTE_SOCKS_PORT REMOTE_PROXY_USER REMOTE_PROXY_PW

podman exec -it gost-proxy-server bash
