version: '3.8'

# v2:
# https://v2.gost.run/en/getting-started/
# https://github.com/ginuerzh/gost
# docker.io/ginuerzh/gost:latest

# v3:
# https://gost.run/en/getting-started/configuration-overview/
# https://github.com/go-gost/gost

services:
  gost-proxy-server:
    container_name: gost-proxy-server
    # image: docker.io/ginuerzh/gost:latest
    # image: docker.io/go-gost/gost:latest
    image: docker.io/aanno/gost:$GOST_VERSION
    # command: -C /config/config.txt
    command: -C /etc/gost/gost.yml
    # not with podman rootless
    # otherwise very difficult to get IP (or use localhost)
    network_mode: "host"
    #ports:
    #  - $REMOTE_PROXY_PORT:$REMOTE_PROXY_PORT
    #  - $REMOTE_SOCKS_PORT:$REMOTE_SOCKS_PORT
    dns:
      # https://de.getflix.com.au/setup/dns-servers/
      # Deutschland - Frankfurt - no vpn
      - 54.93.169.181
      # Großbritannien - London - no vpn
      - 212.71.249.225
      # Dänemark - with vpn
      # - 82.103.129.240

    restart: unless-stopped
    volumes:
      - ./config/gost.yml:/etc/gost/gost.yml:z,ro
      - ./config:/config:z,ro
