FROM localhost/rust

USER root

COPY run-once.sh /home/vscode/

RUN set -ex;\
  cd; \
  dnf -y install \
  https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm; \
  dnf -y install \
  https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm; \
  dnf -y upgrade ; \
  dnf -y install python3-devel \
    patchelf libpq postgresql17 \
    xorg-x11-drv-nvidia-libs xorg-x11-drv-nvidia-cuda \
    --setopt=install_weak_deps=False ; \
  chown $userid:$userid /home/vscode/.venv /home/vscode/run-once.sh;

#   python-setuptools-wheel python3-setuptools_scm+toml python3-setuptools_scm+rich \
#   python3-setuptools-rust  python3-types-setuptools \

USER vscode

ENV SHELL=/bin/bash

RUN set -ex; \
  cd ; \
  source /home/vscode/.bashrc ; \
  pwd ; \
  export PIP_CACHE_DIR=/pip ; \
  echo "export PIP_CACHE_DIR=/pip" >>/home/vscode/.bashrc ; \
  source /home/vscode/.bashrc ; \
  python3 -m venv .venv || true ; \
  source .venv/bin/activate ; \
  # echo "source ~/.venv/bin/activate" >>/home/vscode/.bashrc ; \
  # must be run later
  # ~/.volta/bin/pnpm set -g store-dir /pnpm ; \
  # ~/.volta/bin/pnpm setup ; \
  source /home/vscode/.bashrc ; \
  # all this must be done later - as mounting is delicate on built (tp)
  # pnpm install -g @anthropic-ai/claude-code ; \
  # pip install pre-commit maturin psycopg "psycopg[pool]" pgvector \
  #  "sentence-transformers" ; \
  # caches are not mounted on build (tp) \
  # rm -r /pnpm/* /pip/* || true ; \
  sed -i '/\. "\$HOME\/\.cargo\/env"/d' ~/.bashrc ; \
  source /home/vscode/.bashrc ;

  # must be run later
  # ~/.local/bin/pre-commit install ; \

WORKDIR /workspaces/rust
