from docker.io/library/fedora:39

#  CPackRPM: source dir path '/opt/owntone/mariadb-server' is shorter than
#  debuginfo sources dir path '/usr/src/debug/MariaDB-/src_0'! Source dir path
#  must be longer than debuginfo sources dir path.  Set
#  CPACK_RPM_BUILD_SOURCE_DIRS_PREFIX variable to a shorter value or make
#  source dir path longer.  Required for debuginfo packaging.  See
#  documentation of CPACK_RPM_DEBUGINFO_PACKAGE variable for details.

#error: File not found: /opt/owntone/make-it-longer/mariadb-build/_CPack_Packages/Linux/RPM/mariadb-11.1.3-linux-x86_64/backup/usr/share/man/man1/mariabackup.1\*
#error: File not found: /opt/owntone/make-it-longer/mariadb-build/_CPack_Packages/Linux/RPM/mariadb-11.1.3-linux-x86_64/backup/usr/share/man/man1/mariadb-backup.1\*
#error: File not found: /opt/owntone/make-it-longer/mariadb-build/_CPack_Packages/Linux/RPM/mariadb-11.1.3-linux-x86_64/backup/usr/share/man/man1/mbstream.1\*
#    File not found: /opt/owntone/make-it-longer/mariadb-build/_CPack_Packages/Linux/RPM/mariadb-11.1.3-linux-x86_64/backup/usr/share/man/man1/mariabackup.1\*
#    File not found: /opt/owntone/make-it-longer/mariadb-build/_CPack_Packages/Linux/RPM/mariadb-11.1.3-linux-x86_64/backup/usr/share/man/man1/mariadb-backup.1\*
#    File not found: /opt/owntone/make-it-longer/mariadb-build/_CPack_Packages/Linux/RPM/mariadb-11.1.3-linux-x86_64/backup/usr/share/man/man1/mbstream.1\*

# https://jira.mariadb.org/projects/MDEV/issues/MDEV-32741
COPY CPackRPM.cmake.diff /root/

RUN set -ex;\
  mkdir /opt/owntone || true; \
  cd; \
  echo "fastestmirror=1" >>/etc/dnf/dnf.conf; \
  #dnf -y install \
  #https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm; \
  #dnf -y install \
  #https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm; \
  dnf -y install dnf-plugins-core; \
  dnf -y install patch cmake; \
  patch -d/ -p0 </root/CPackRPM.cmake.diff; \
  dnf -y builddep mariadb-server; \
  dnf -y install git snappy-devel csnappy-devel libpmem-devel lzo-devel bzip2-devel rpm-build rpm ; \
  mkdir /opt/owntone/make-it-longer || true; \
  cd /opt/owntone/make-it-longer; \
  git clone --depth 10 --branch 11.1 https://github.com/MariaDB/server.git mariadb-server; \
  mkdir mariadb-build; \
  cd mariadb-build; \
  cmake -DRPM=fedora ../mariadb-server; \
  make; \
  make package;
  
# CMD [ "/usr/sbin/owntone",  "-d",  "5",  "-f" ]
# ENTRYPOINT [ "/usr/sbin/owntone", "-d", "5", "-f" ]

