from docker.io/library/fedora:39

#  CPackRPM: source dir path '/opt/owntone/mariadb-server' is shorter than
#  debuginfo sources dir path '/usr/src/debug/MariaDB-/src_0'! Source dir path
#  must be longer than debuginfo sources dir path.  Set
#  CPACK_RPM_BUILD_SOURCE_DIRS_PREFIX variable to a shorter value or make
#  source dir path longer.  Required for debuginfo packaging.  See
#  documentation of CPACK_RPM_DEBUGINFO_PACKAGE variable for details.

#error: File not found: /opt/owntone/make-it-longer/mariadb-build/_CPack_Packages/Linux/RPM/mariadb-11.1.3-linux-x86_64/backup/usr/share/man/man1/mariabackup.1\*
#error: File not found: /opt/owntone/make-it-longer/mariadb-build/_CPack_Packages/Linux/RPM/mariadb-11.1.3-linux-x86_64/backup/usr/share/man/man1/mariadb-backup.1\*
#error: File not found: /opt/owntone/make-it-longer/mariadb-build/_CPack_Packages/Linux/RPM/mariadb-11.1.3-linux-x86_64/backup/usr/share/man/man1/mbstream.1\*
#    File not found: /opt/owntone/make-it-longer/mariadb-build/_CPack_Packages/Linux/RPM/mariadb-11.1.3-linux-x86_64/backup/usr/share/man/man1/mariabackup.1\*
#    File not found: /opt/owntone/make-it-longer/mariadb-build/_CPack_Packages/Linux/RPM/mariadb-11.1.3-linux-x86_64/backup/usr/share/man/man1/mariadb-backup.1\*
#    File not found: /opt/owntone/make-it-longer/mariadb-build/_CPack_Packages/Linux/RPM/mariadb-11.1.3-linux-x86_64/backup/usr/share/man/man1/mbstream.1\*

# https://jira.mariadb.org/projects/MDEV/issues/MDEV-32741
COPY CPackRPM.cmake.diff /root/

RUN set -ex;\
  mkdir /opt/owntone || true; \
  cd; \
  echo "fastestmirror=1" >>/etc/dnf/dnf.conf; \
  dnf -y install patch cmake tree; \
  # patch -d/ -p0 </root/CPackRPM.cmake.diff; \
  # dnf -y builddep mariadb-server; \
  # https://mariadb.com/kb/en/building-the-galera-wsrep-package-on-fedora/ \
  dnf -y install automake gcc gcc-c++ boost-devel check-devel glibc-devel openssl-devel ; \
  mkdir /opt/owntone/make-it-longer || true; \
  cd /opt/owntone/make-it-longer; \
  curl https://releases.galeracluster.com/galera-4/source/galera-4-26.4.16.tar.gz | tar xvz;\
  cd galera-4-26.4.16;\
  cmake . ;\
  make package;\
  tar xvfz galera-4-26.4.16-Linux-x86_64.tar.gz;\
  cd galera-4-26.4.16-Linux-x86_64;\
  tree .; 
  
# CMD [ "/usr/sbin/owntone",  "-d",  "5",  "-f" ]
# ENTRYPOINT [ "/usr/sbin/owntone", "-d", "5", "-f" ]

