from docker.io/library/fedora:43

# ENV userid=1001
ENV userid=1000
RUN useradd -m -d /home/vscode -s /bin/bash -G wheel,users -p vscode -u $userid vscode

COPY .bashrc .gitconfig /home/vscode/

RUN set -ex;\
  cd; \
  echo "fastestmirror=1" >>/etc/dnf/dnf.conf; \
  dnf -y install \
  https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm; \
  dnf -y install \
  https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm; \
  dnf -y upgrade ; \
  dnf -y install @development-tools pkgconf pkgconf-pkg-config patch \
    meson ninja-build \
    which tree procs nano top git file iproute strace \
    gawk uv ripgrep ugrep ag yq jq \
    gcc gcc-c++ make xz \
    automake autoconf gcc gcc-c++ boost-devel check-devel glibc-devel openssl-devel \
    dbus-devel gettext libtool cmake conan vcpkg \
    --setopt=install_weak_deps=False ; \
  dnf -y install \
  # gmrender \
  gstreamer1-devel  gstreamer1-plugins-base  gstreamer1-plugins-good \
  gstreamer1-plugins-bad-freeworld gstreamer1-plugins-ugly gstreamer1-plugin-libav \
  libupnp-devel pipewire-pulseaudio pipewire-gstreamer pipewire-devel \
  # mariadb
  snappy-devel csnappy-devel lzo-devel bzip2-devel rpm-build rpm nvml-devel \
  # libpmem-devel
  # nymphcast (partly)
  poco-devel freetype-devel ffmpeg-devel libatomic \
  # owntone
  bison flex \
  sqlite-devel libconfuse-devel libunistring-devel libxml2-devel mxml-devel libevent-devel \
  libgcrypt-devel zlib-ng-devel alsa-lib-devel ffmpeg-devel \
  libplist-devel libsodium-devel json-c-devel libwebsockets-devel \
  libcurl-devel protobuf-c-devel \
  # snapcast
  pipewire-devel pipewire-pulseaudio  dbus-devel \
  pipewire-jack-audio-connection-kit-devel portaudio-devel \
  alsa-lib-devel avahi-devel libatomic libvorbis-devel \
  opus-devel pulseaudio-libs-devel\
  flac-devel soxr-devel libstdc++-static expat-devel \
  # spotifyd
  pipewire-devel pipewire-pulseaudio  dbus-devel \
  pipewire-jack-audio-connection-kit-devel portaudio-devel \
  # taglib2
  cppunit-devel utf8cpp-devel  zlib-ng-compat-devel  wavpack-devel  libvorbis-devel \
  # upmpdcli
  libmp4v2-devel libogg-devel flac-devel libaiff-devel pkgconf  pkgconf-pkg-config \
  speex-devel libmpcdec-devel opus-devel \
  libsamplerate-devel zlib-devel alsa-lib-devel pipewire-pulseaudio pipewire-devel \
  flac-devel \
  --setopt=install_weak_deps=False --skip-unavailable ; \
  # replace full libcurl with minimal
  dnf install -y --allowerasing libcurl-minimal; \
  mkdir -p /home/vscode ; \
  cd /home/vscode ; \
  chown $userid:$userid /home/vscode .gitconfig .bashrc .volta || true; \
  # chown -R vscode:users /build; \
  chmod a+x /build/*.sh ; \
  echo "vscode:vscode" | chpasswd ; \
  echo "root:root" | chpasswd ; \
  id

USER vscode
WORKDIR /workspaces/cpp

RUN \
  cd ; \
  pwd ; \
  curl https://get.volta.sh | bash ; \
  # volta install node ; \
  # volta install pnpm ; \
  ls ; \
  id

