version: '3.3'
services:
  keycloak_container:
    image: jboss/keycloak
    container_name: keycloak-2
    # depends_on: 
    #  - letsencrypt-companion
    #  - proxy
    # ports:
    #  - 8080:8080
    #volumes:
    #  - ${BASE}/gitbucket-data:/gitbucket
    environment:
      - PROXY_ADDRESS_FORWARDING=true
      # defaults to:
      # -server -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m 
      # -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true
      #- JAVA_OPTS=-Xmx512m
      - DB_VENDOR=mariadb
      - DB_ADDR=172.18.0.1
      - DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin1234
    networks:
      - proxy-tier
    restart: always

networks:
  proxy-tier:
    external:
      name: nginx-proxy

