from docker.io/library/fedora:42

# ENV userid=1001
ENV userid=1000
RUN useradd -m -d /home/vscode -s /bin/bash -G wheel,users -p vscode -u $userid vscode

COPY .bashrc .gitconfig /home/vscode/

RUN set -ex;\
  cd; \
  echo "fastestmirror=1" >>/etc/dnf/dnf.conf; \
  # dnf -y install patch cmake tree; \
  # https://github.com/taglib/taglib/blob/master/INSTALL.md \
  # dnf -y install automake gcc gcc-c++ boost-devel check-devel glibc-devel openssl-devel \
  #  git cppunit-devel utf8cpp-devel  zlib-ng-compat-devel  wavpack-devel  libvorbis-devel \
  #  libmp4v2-devel libogg-devel flac-devel libaiff-devel pkgconf  pkgconf-pkg-config \
  #  speex-devel libmpcdec-devel opus-devel ; \
  dnf -y upgrade ; \
  dnf -y install @development-tools pkgconf pkgconf-pkg-config patch \
    which tree procs nano top git file iproute strace \
    gawk uv ripgrep ugrep ag yq jq \
    make ; \
  ln -fs /usr/share/zoneinfo/Europe/Berlin /etc/localtime; \
  mkdir -p /home/vscode ; \
  cd /home/vscode ; \
  chown $userid:$userid /home/vscode .gitconfig .bashrc .volta ; \
  # volta install is difficult
  # chown -R $userid:$userid .volta ; \
  chmod a+x /build/*.sh ; \
  echo "vscode:vscode" | chpasswd ; \
  echo "root:root" | chpasswd ; \
  id

USER vscode
WORKDIR /workspaces/rust

RUN \
  cd ; \
  pwd ; \
  bash /build/volta.sh; \
  # https://pdm-project.org/en/latest/ \
  # python3 /build/install-pdm.py ; \
  source ~/.bashrc ; \
  volta install node ; \
  volta install pnpm ; \
  /build/rustup.sh -y ; \
  rustup update ; \
  sed -i '/\. "\$HOME\/\.cargo\/env"/d' ~/.bashrc ; \
  source ~/.bashrc ; \
  ls ; \
  id

