CREATE DATABASE `${MYSQL_USER}`;
CREATE USER '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT USAGE ON `${MYSQL_DATABASE}`.* TO '$MYSQL_USER'@'%';
GRANT ALL privileges ON `${MYSQL_DATABASE}`.* TO '$MYSQL_USER'@'%';
FLUSH privileges;
