version: '3.7'

services:
  db:
    image: mariadb:10.6
    # --skip-innodb-read-only-compressed: https://github.com/nextcloud/server/issues/25436
    command: [
      "--transaction-isolation=READ-COMMITTED", "--log-bin=mysqld-bin",
      "--binlog-format=ROW", "--log_bin_compress",
      "--skip-innodb-read-only-compressed"
    ]
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
      - ./backup:/backup:z
    env_file:
      - db.env
    networks:
      - proxy-tier

volumes:
  db:

# https://stackoverflow.com/questions/38088279/communication-between-multiple-docker-compose-projects
# https://docs.docker.com/compose/networking/
# docker network create proxy-tier
networks:
    proxy-tier:
        external: true
        name: proxy-tier

