[supervisord]
nodaemon=true
user=openvpn
loglevel=info
pidfile=/tmp/supervisord.pid

[program:openvpn]
command=/usr/sbin/openvpn --config /config/getflix-vpnonly.ovpn --auth-user-pass /config/passfile
directory=/config
autostart=true
autorestart=true
startsecs=5
startretries=3
stderr_logfile=/dev/stderr
stdout_logfile=/dev/stdout
stderr_logfile_maxbytes=0
stdout_logfile_maxbytes=0

[program:gost]
command=gost -C /config/gost.yml
directory=/config
autostart=true
autorestart=true
startsecs=5
startretries=3
stderr_logfile=/dev/stderr
stdout_logfile=/dev/stdout
stderr_logfile_maxbytes=0
stdout_logfile_maxbytes=0
