version: '3.7'

services:
  coturn:
    # build: docker/coturn
    # https://hub.docker.com/r/coturn/coturn
    # default port: 3478
    image: docker.io/coturn/coturn
    # ok here (tp)
    network_mode: host
    networks:
        - proxy-tier
    # TODO: variables from 'environment:' do not work here
    # unsure: --prod --verbose
    command: [
             "turnserver", "--fingerprint", "--prod", "--verbose",
             "--external-ip=${SERVER_EXTERNAL_IP}",
             "--listening-ip=${SERVER_EXTERNAL_IP}",
             "--use-auth-secret", 
             "--static-auth-secret=${COTURN_SECRET}",
             "--realm=${COTURN_FQN}",
             "--no-multicast-peers", "--no-tls", "--no-dtls",
             "--log-file=stdout", "-n", "--no-cli"
             ]
    # according to https://hub.docker.com/r/coturn/coturn this should speed up persistence
    volumes:
      - type: tmpfs
        target: /var/lib/coturn
        tmpfs:
          # max bytes
          size: 100000
    restart: unless-stopped

# https://stackoverflow.com/questions/38088279/communication-between-multiple-docker-compose-projects
# https://docs.docker.com/compose/networking/
networks:
    proxy-tier:
        external: true
        name: proxy-tier

