version: '3.7'

services:
  spreedbackend:
    # build: .
    image: docker.io/aanno/nextcloud-spreed-signaling:v0.3.0
    volumes:
      # from https://github.com/strukturag/nextcloud-spreed-signaling
      - ./server.conf:/config/server.conf:z,ro
    # network_mode: host
    networks:
        - proxy-tier
    restart: unless-stopped
    depends_on:
      - nats
      - janus
      - coturn
  nats:
    # image: nats:2.1
    image: docker.io/nats:2.3.2-alpine3.14
    volumes:
      # from https://github.com/strukturag/nextcloud-spreed-signaling
      - ./gnatsd.conf:/config/gnatsd.conf:z,ro
    command: ["-c", "/config/gnatsd.conf"]
    # network_mode: host
    networks:
        - proxy-tier
    restart: unless-stopped
  janus:
    # build: docker/janus
    image: docker.io/aanno/janus-gateway:v0.11.1
    # TODO: "-S", "coturn:5349" does not work (because of host mode)
    command: ["janus", "-6", "--full-trickle", "-S", "coturn:3478"]
    # network_mode: host
    networks:
        - proxy-tier
    restart: unless-stopped
    depends_on:
      - coturn
  coturn:
    # build: docker/coturn
    # https://hub.docker.com/r/coturn/coturn
    # default port: 5349
    image: docker.io/coturn/coturn
    # ok here (tp)
    # network_mode: host
    networks:
        - proxy-tier
    # TODO: variables from 'environment:' do not work here
    command: [
             "/bin/sh", "-c", "turnserver",  "--prod",  "--fingerprint",
             "--use-auth-secret", 
             "--static-auth-secret=1e95cf79ccaf812f2498c4a2470a6dd5e62eeb2451d34e819ea12602b8d1bf67",
             "--realm=signaling.example.com",
             "--no-multicast-peers", "--no-tls", "--no-dtls",
             "--log-file=stdout", "-n", "--no-cli"
             ]
    environment:
      REALM: signaling.example.com
      # STATIC_SECRET: openssl rand -hex 32
      STATIC_SECRET: 1e95cf79ccaf812f2498c4a2470a6dd5e62eeb2451d34e819ea12602b8d1bf67
    # according to https://hub.docker.com/r/coturn/coturn this should speed up persistence
    volumes:
      - type: tmpfs
        target: /var/lib/coturn
        tmpfs:
          # bytes
          size: 100000
    restart: unless-stopped

# https://stackoverflow.com/questions/38088279/communication-between-multiple-docker-compose-projects
# https://docs.docker.com/compose/networking/
networks:
    proxy-tier:
        external: true
        name: proxy-tier

