services:
  coredns:
    image: docker.io/coredns/coredns
    dns: 10.89.4.1
    # It is not needed to expose the DNS server - it is local to the dnsexample network
    # ports:
    #   - 53/udp
    #   - 53/tcp
    volumes:
      - ./coredns:/etc/coredns:z,ro
    networks:
      dnsexample:
        ipv4_address: 10.89.4.4
    command: -conf /etc/coredns/Corefile
  fedora:
    image: docker.io/fedora
    # dns: 10.89.4.4
    # dns: none
    # volumes:
    #   - ./resolv.conf:/etc/resolv.conf:z,ro
    depends_on: 
      - coredns
    networks:
      dnsexample:
        # ipv4_address: 10.89.4.5
    command: ["sleep", "10000"]

# create with:
# podman network create --subnet 10.89.4.0/24 --gateway 10.89.4.1 --dns 10.89.4.4 --driver bridge dnsexample
networks:
  dnsexample: 
    external: true

