version: '3.3'
services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    labels: 
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    container_name: proxy-2
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d
      - ./proxy/vhost.d:/etc/nginx/vhost.d
      - ./proxy/html:/usr/share/nginx/html
      - ./proxy/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - ENABLE_IPV6=true
    networks:
      - proxy-tier
    restart: always

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-companion
    depends_on: 
      - proxy
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d
      - ./proxy/vhost.d:/etc/nginx/vhost.d
      - ./proxy/html:/usr/share/nginx/html
      - ./proxy/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

#  letsencrypt-companion-old:
#    image: alastaircoote/docker-letsencrypt-nginx-proxy-companion
#    container_name: letsencrypt-companion
#    volumes_from:
#      - proxy
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock:ro
#      - ./proxy/certs:/etc/nginx/certs:rw
#    restart: always

#  web:
#    image: nginx
#    container_name: nextcloud_webserver
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#    links:
#      - app
#      - collabora
#    volumes_from:
#      - app
#    environment:
#      - VIRTUAL_HOST=${DOMAIN}
#      - VIRTUAL_NETWORK=nginx-proxy
#      - VIRTUAL_PORT=80
#      - LETSENCRYPT_HOST=${DOMAIN}
#      - LETSENCRYPT_EMAIL=${EMAIL}
#    networks:
#      - proxy-tier
#    restart: always

  app:
    image: aanno/nextcloud:${VERSION}-apache
    container_name: nextcloud_apache
    depends_on: 
      - letsencrypt-companion
      - proxy
      - redis
      - collabora
    volumes:
      - ${BASE}/apps:${TARGET}/custom_apps
      - ${BASE}/config:${TARGET}/config
      - ${BASE}/data:${TARGET}/data
    environment:
      - BASE_PATH=/nextcloud
      - VIRTUAL_HOST=${DOMAIN}
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${DOMAIN}
      - LETSENCRYPT_EMAIL=${EMAIL}
    networks:
      - proxy-tier
    restart: always

  redis:
    image: redis
    container_name: redis-2
    networks:
      - proxy-tier
    restart: always

  collabora:
    image: collabora/code
    container_name: collabora-2
    cap_add:
      - MKNOD
    environment:
      - domain=${DOMAIN}
    networks:
      - proxy-tier
    restart: always

networks:
  proxy-tier:
    external:
      name: nginx-proxy

